### ISSUE TITLE
Delete doesn't seem to be working...

### ISSUE THREAD

**Issue by ghost** [godfat/rest-graph#1]
Im using this code:
fb_access = RestGraph.new(:access_token => access_token)
@results = fb_access.delete("131386346878718_132279686787234")

**Comment by godfat** [comment]
I just tried it a moment before, and I think this may be a facebook or network proxy or something's issue that delete didn't work right.

<pre>curl -v -X DELETE 'https://graph.facebook.com/123_456?access_token=789'</pre>


Above code didn't work either.
Perhaps you could use this workaround:

<pre>fb_access.post("131386346878718_132279686787234", :method => 'delete')</pre>


At least this works for me.

**Comment by outstand** [comment]
Thanks for the swift response... I am already using this workaround.

**Comment by godfat** [comment]
Thanks for your report. Let's see if there's a chance to fix this..
