### ISSUE TITLE
Rails.cache + DalliStore

### ISSUE THREAD

**Issue by Shinta** [godfat/rest-graph#8]
Hello,

I use Memcached gem Dalli in my project, and Rest-Graph doesn't work out of the box with this gem.

So I did a monkeypath:

``` ruby
class RestGraph
  def cache_assign opts, uri, value
    return unless cache
    if cache.is_a?(ActiveSupport::Cache::DalliStore)
      cache.write(cache_key(opts, uri), value)
    else
      cache[cache_key(opts, uri)] = value
    end
  end
  def cache_get opts, uri
    return unless cache
    start_time = Time.now
    if cache.is_a?(ActiveSupport::Cache::DalliStore)
      cache.read(cache_key(opts, uri)).tap{ |result|
        log(Event::CacheHit.new(Time.now - start_time, uri)) if result
      }
    else
      cache[cache_key(opts, uri)].tap{ |result|
        log(Event::CacheHit.new(Time.now - start_time, uri)) if result
      }
    end
  end
  def cache_for opts, uri, meth, value
    return unless cache
    # fake post (opts[:post] => true) is considered get and need cache
    return if meth != :get unless opts[:post]
    expires = opts[:expires_in] || expires_in
    if cache.is_a?(ActiveSupport::Cache::DalliStore)
      if expires.kind_of?(Fixnum)
        cache.write(cache_key(opts, uri), value, :expires_in => expires)
      else
        cache_assign(opts, uri, value)
      end
    else
      if expires.kind_of?(Fixnum) && cache.method(:store).arity == -3
        cache.store(cache_key(opts, uri), value, :expires_in => expires)
      else
        cache_assign(opts, uri, value)
      end
    end
  end
end
```

It's working now.

Please feel free in fix anything (or make more elegant) I did wrong or add it to the source.

Sorry if this is dirty I just need it to work it out fast.

Thanks and keep up with the good work.

**Comment by godfat** [comment]
You might want to take a look at [RailsUtil](https://github.com/godfat/rest-graph/blob/master/lib/rest-graph/rails_util.rb) if you're using Rails.
Which would include this module to make ActiveSupport work:

``` ruby
  module RailsCache
    def [] key ; read(key) ; end
    def []= key, value; write(key, value) ; end
    def store key, value,
              options={}; write(key, value, options); end
  end
```

This might not be a good solution, either. But I really hope
people could use some unified interface for key/value stores.
For example, there's [moneta](https://github.com/minad/moneta) which tries to do this.

Please let me know if this works for you, and if you're
using ActiveSupport without using Rails?

Thanks for using rest-graph and report this to me.
